# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_resolver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapper',
            name='mobile_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='urlmapper',
            name='slug',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='urlmapper',
            name='tablet_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
